-- Legacy database migration guide
--
-- Do not run this file blindly against a live database. The old schema allowed
-- nullable/text user IDs and duplicate swipe rows, so a safe migration depends
-- on the data already stored in your project. Back up user_swipes, audit invalid
-- or duplicate records, then use supabase-schema.sql as the target definition.
--
-- Required outcomes before deploying the app:
--   1. user_swipes.user_id is UUID NOT NULL and references auth.users(id)
--   2. one row exists at most for each (user_id, house_id)
--   3. the only user_swipes RLS policy is ownership-based FOR ALL
--   4. all nullable or invalid legacy rows are resolved intentionally
--
-- This guide is deliberately non-executable to avoid deleting or silently
-- reassigning production data. Create and review a project-specific migration
-- before changing an existing database.
